words = [
    "adblock",
    "adiaeresis",
    "afreakk",
    "ahci",
    "anr",
    "asciicircum",
    "asciitilde",
    "authfile",
    "autoconfig",
    "autocopy",
    "autoreload",
    "bibata",
    "birdee",
    "bksl",
    "bluetui",
    "bootable",
    "borderless",
    "braceleft",
    "braceright",
    "bracketleft",
    "bracketright",
    "btrfs",
    "cachix",
    "capslock",
    "cdi",
    "cdrom",
    "charachorder",
    "chmod",
    "chown",
    "chromakey",
    "clippy",
    "contextmenu",
    "conv",
    "coreutils",
    "darkwindow",
    "deadnix",
    "deja",
    "dejavu",
    "dialout",
    "difftastic",
    "direnv",
    "disko",
    "dno",
    "dsp",
    "efi",
    "entersearch",
    "esac",
    "euo",
    "everforest",
    "evolog",
    "exclam",
    "executehostcommand",
    "eza",
    "filechooser",
    "fileselect",
    "filesize",
    "findutils",
    "freedesktop",
    "fsmonitor",
    "fzf",
    "gamescope",
    "ghostty",
    "gpt",
    "greasemonkey",
    "hypr",
    "hyprctl",
    "hyprland",
    "hyprnotify",
    "hyprpaper",
    "hyprpicker",
    "hyprshutdown",
    "hyprsunset",
    "hyprwm",
    "jdtls",
    "jjdescription",
    "jjui",
    "jujutsu",
    "kdl",
    "keybind",
    "keybinds",
    "keyd",
    "keyhint",
    "keyids",
    "kpad",
    "kpdl",
    "kpdv",
    "kpen",
    "kpeq",
    "kpmu",
    "kpsu",
    "kvm",
    "lanczos",
    "linters",
    "lsblk",
    "lsgt",
    "lvm",
    "lvs",
    "micha",
    "mkdir",
    "mktemp",
    "mostafaqanbaryan",
    "natively",
    "nestix",
    "networkmanager",
    "nixd",
    "nixos",
    "nixpkgs",
    "nmcli",
    "nmlk",
    "nnbsp",
    "noatime",
    "noinfo",
    "nonwhitespace",
    "noto",
    "numbersign",
    "numtide",
    "nuon",
    "nushell",
    "nvme",
    "odiaeresis",
    "oflag",
    "oneshot",
    "oplog",
    "outfoxxed",
    "overloadt",
    "ovmf",
    "oxalica",
    "parenleft",
    "parenright",
    "paus",
    "pgdn",
    "pgup",
    "pinentry",
    "pipefail",
    "pkgs",
    "poweroff",
    "progs",
    "prsc",
    "qml",
    "qmlls",
    "quotedbl",
    "qutebrowser",
    "readlink",
    "remarshal",
    "renamepane",
    "renametab",
    "revsets",
    "rightalt",
    "ripgrep",
    "rtsx",
    "sclk",
    "screencopy",
    "scrolloff",
    "sda",
    "sdmmc",
    "searchengines",
    "secmem",
    "sessionizer",
    "shader",
    "shaders",
    "sigpipe",
    "srcs",
    "ssharp",
    "statix",
    "statusline",
    "stdenv",
    "stepless",
    "stylix",
    "substituters",
    "subvol",
    "subvolume",
    "subvolumes",
    "symbolsshift",
    "systemctl",
    "tabpad",
    "tabstop",
    "termcmd",
    "termfilechooser",
    "thinkpad",
    "thirdparties",
    "tinymist",
    "tlde",
    "treefmt",
    "ublock",
    "udiaeresis",
    "umask",
    "umount",
    "unifont",
    "unityhub",
    "unyank",
    "uwsm",
    "verible",
    "verilog",
    "vfat",
    "vmm",
    "vrr",
    "wlib",
    "wpctl",
    "xdg",
    "xdgdesktopportal",
    "xhci",
    "xkb",
    "xxxxxx",
    "yazi",
    "yubi",
    "zellij",
    "zjstatus",
    "zoxide",
]
