# This file was automatically generated by the Modulix flake generator
# and will be overwritten without warning on subsequent runs of the generator.
{
  inputs = {
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    file-manager-theme = {
      url = "github:Chromium-3-Oxide/everforest-medium.yazi";
      flake = false;
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    hy3 = {
      url = "github:outfoxxed/hy3/hl0.52.0";
      inputs.hyprland.follows = "hyprland";
    };
    hypr-darkwindow = {
      url = "github:micha4w/Hypr-DarkWindow/v0.52.2";
      inputs.hyprland.follows = "hyprland";
    };
    hyprland.url = "github:hyprwm/Hyprland/v0.52.2";
    hyprland-easymotion = {
      url = "github:zakk4223/hyprland-easymotion/d46fa73d";
      inputs = {
        hyprland.follows = "hyprland";
        nixpkgs.follows = "hyprland/nixpkgs";
      };
    };
    impermanence.url = "github:nix-community/impermanence";
    modulix = {
      url = "github:Noah765/modulix";
      inputs = {
        home-manager.follows = "home-manager";
        nixpkgs.follows = "nixpkgs";
      };
    };
    nix-index-database = {
      url = "github:nix-community/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    qutebrowser-abp-filters-anti-cv = {
      url = "file+https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt";
      flake = false;
    };
    qutebrowser-annoyances = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/annoyances.min.txt";
      flake = false;
    };
    qutebrowser-badware = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/badware.min.txt";
      flake = false;
    };
    qutebrowser-easylist = {
      url = "file+https://easylist.to/easylist/easylist.txt";
      flake = false;
    };
    qutebrowser-easylistgermany = {
      url = "file+https://easylist.to/easylistgermany/easylistgermany.txt";
      flake = false;
    };
    qutebrowser-easyprivacy = {
      url = "file+https://easylist.to/easylist/easyprivacy.txt";
      flake = false;
    };
    qutebrowser-experimental = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/experimental.min.txt";
      flake = false;
    };
    qutebrowser-fanboy-annoyance = {
      url = "file+https://secure.fanboy.co.nz/fanboy-annoyance.txt";
      flake = false;
    };
    qutebrowser-filters = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/filters.min.txt";
      flake = false;
    };
    qutebrowser-privacy = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/privacy.min.txt";
      flake = false;
    };
    qutebrowser-quick-fixes = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.min.txt";
      flake = false;
    };
    qutebrowser-serverlist = {
      url = "file+https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext";
      flake = false;
    };
    qutebrowser-unbreak = {
      url = "file+https://ublockorigin.github.io/uAssetsCDN/filters/unbreak.min.txt";
      flake = false;
    };
    qutebrowser-urlhaus-filter-vivaldi-online = {
      url = "file+https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-vivaldi-online.txt";
      flake = false;
    };
    stylix = {
      url = "github:nix-community/stylix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs: inputs.modulix.modulixSystems (import ./config.nix) inputs;
}
